// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnyBoRHb1kxP8J-BFbAIGJ83JdP6lAVWE',
    appId: '1:717537004014:web:b801dad26f7e4304ede6ff',
    messagingSenderId: '717537004014',
    projectId: 'engez-1725b',
    authDomain: 'engez-1725b.firebaseapp.com',
    storageBucket: 'engez-1725b.firebasestorage.app',
    measurementId: 'G-X1DHQ1TQJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOirUpHu3Vku7E4ljWfzsYHtFMV5ptZhQ',
    appId: '1:717537004014:android:6d97903aa42e1a68ede6ff',
    messagingSenderId: '717537004014',
    projectId: 'engez-1725b',
    storageBucket: 'engez-1725b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADSeJaz_yIB5EVJwDYOawaJm4EGIZUgS4',
    appId: '1:717537004014:ios:f814828310f46769ede6ff',
    messagingSenderId: '717537004014',
    projectId: 'engez-1725b',
    storageBucket: 'engez-1725b.firebasestorage.app',
    androidClientId: '717537004014-3kjkngj35bjfq5f1qbo5j1h1799hhkt3.apps.googleusercontent.com',
    iosClientId: '717537004014-itfhl631g67h98dl2r2b45qrjvmaohgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.engez',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADSeJaz_yIB5EVJwDYOawaJm4EGIZUgS4',
    appId: '1:717537004014:ios:f814828310f46769ede6ff',
    messagingSenderId: '717537004014',
    projectId: 'engez-1725b',
    storageBucket: 'engez-1725b.firebasestorage.app',
    androidClientId: '717537004014-3kjkngj35bjfq5f1qbo5j1h1799hhkt3.apps.googleusercontent.com',
    iosClientId: '717537004014-itfhl631g67h98dl2r2b45qrjvmaohgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.engez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnyBoRHb1kxP8J-BFbAIGJ83JdP6lAVWE',
    appId: '1:717537004014:web:5e147a7dbe94f7f0ede6ff',
    messagingSenderId: '717537004014',
    projectId: 'engez-1725b',
    authDomain: 'engez-1725b.firebaseapp.com',
    storageBucket: 'engez-1725b.firebasestorage.app',
    measurementId: 'G-Q582JZFGYS',
  );
}
